# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Project05' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 4.0.0'
  pod 'PullToRefreshKit', '~> 0.8.6'
  # Pods for Project05
  

end
