# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'Project03' do
  use_frameworks!

pod 'Moya', '~> 11.0.2'
pod 'Kingfisher', '~> 4.8.0'
pod 'IQKeyboardManagerSwift', '4.0.10'

end
