# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Project03' do
  use_frameworks!

pod 'Alamofire', '~> 4.4.0'
pod 'Kingfisher', '~> 3.10.1'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
pod 'IQKeyboardManagerSwift', '4.0.10'

end
