# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Project04-Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project04-Extension
  pod 'PullToRefreshKit', '~> 0.8.6'
  pod 'SnapKit', '~> 4.0.0'
  
end
