# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Project01' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
   pod 'Moya', '~> 11.0.2'
   pod 'SnapKit', '~> 4.0.0'
   pod 'Kingfisher', '~> 4.8.0'
   pod 'PullToRefreshKit', '~> 0.8.6'
   
  # Pods for Project01

end
